from decimal import Decimal

MAX_NAME_LENGTH = 100
MAX_TEXT_LENGTH = 500
MAX_DIGITS_DECIMAL = 10
DECIMAL_PLACES = 2
MIN_PRICE = Decimal(1)
MAX_WORDS_COUNT_DISPLAY = 10
MAX_DISCOUNT_PERCENT = 70
MIN_DISCOUNT_PERCENT = 1
MIN_TAX_PERCENT = 1
STRIPE_ID_MAX_LENGTH = 100
