# Generated by Django 3.2 on 2025-05-29 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('stripe_id', models.CharField(blank=True, max_length=100, null=True)),
                ('percent_off', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(1)], verbose_name='процент скидки')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('stripe_id', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='процент налога')),
            ],
            options={
                'verbose_name': 'налог',
                'verbose_name_plural': 'налоги',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
