# Generated by Django 3.2 on 2025-05-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_discount_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='orders', to='items.Discount', verbose_name='скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='orders', to='items.Tax', verbose_name='налоги'),
        ),
    ]
