# Generated by Django 3.2 on 2025-05-30 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20250529_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent_off',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(70)], verbose_name='процент скидки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='order', to='items.Discount', verbose_name='скидки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order', to='items.Item', verbose_name='товары'),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='order', to='items.Tax', verbose_name='налоги'),
        ),
    ]
